name: Check Server Status

on:
  schedule:
    - cron: '*/10 * * * *'  # A cada 10 minutos
  workflow_dispatch:

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check server status
        run: |
          SERVER_URLS=("https://example.com" "https://example2.com")
          STATUS_FILE="status.json"
          echo "{" > $STATUS_FILE
          for URL in "${SERVER_URLS[@]}"; do
            HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL")
            if [ "$HTTP_STATUS" -eq 200 ]; then
              STATUS="online"
            else
              STATUS="offline"
            fi
            echo "\"$(basename $URL)\": \"$STATUS\"," >> $STATUS_FILE
          done
          echo "}" >> $STATUS_FILE

      - name: Commit status file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add status.json
          git commit -m "Update server status"
          git push
