name: Check Server Status

on:
  schedule:
    - cron: '*/5 * * * *'  # Verifica a cada 5 minutos

jobs:
  check_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run status check script
        run: |
          python3 check_status.py
