name: Atualizar Status dos Servidores

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Atualizar status dos servidores
      run: |
        python3 update_status.py  # Script Python que vai atualizar o arquivo status.json

    - name: Commit e Push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add status.json
        git commit -m "Atualizando status dos servidores"
        git push
